# coding: utf-8

# flake8: noqa
from __future__ import absolute_import
# import models into model package
from swagger_server.models.api_anomalydetection_body import ApiAnomalydetectionBody
from swagger_server.models.api_dataenrichment_body import ApiDataenrichmentBody
from swagger_server.models.api_datatransformation_body import ApiDatatransformationBody
from swagger_server.models.api_habitats_body import ApiHabitatsBody
from swagger_server.models.api_temporalanalysis_body import ApiTemporalanalysisBody
from swagger_server.models.api_trainmodel_body import ApiTrainmodelBody
from swagger_server.models.augmentation_remotesensing_body import AugmentationRemotesensingBody
from swagger_server.models.caching_body import CachingBody
from swagger_server.models.dataquality_body import DataqualityBody
from swagger_server.models.detection_result import DetectionResult
from swagger_server.models.error_response import ErrorResponse
from swagger_server.models.inline_response200 import InlineResponse200
from swagger_server.models.inline_response2001 import InlineResponse2001
from swagger_server.models.inline_response20010 import InlineResponse20010
from swagger_server.models.inline_response2002 import InlineResponse2002
from swagger_server.models.inline_response2002_data import InlineResponse2002Data
from swagger_server.models.inline_response2003 import InlineResponse2003
from swagger_server.models.inline_response2004 import InlineResponse2004
from swagger_server.models.inline_response2005 import InlineResponse2005
from swagger_server.models.inline_response2006 import InlineResponse2006
from swagger_server.models.inline_response2007 import InlineResponse2007
from swagger_server.models.inline_response2008 import InlineResponse2008
from swagger_server.models.inline_response2009 import InlineResponse2009
from swagger_server.models.inline_response200_data import InlineResponse200Data
from swagger_server.models.machine_learning_model import MachineLearningModel
from swagger_server.models.machine_learning_model_hyperparameters import MachineLearningModelHyperparameters
from swagger_server.models.mapping_mapbox_body import MappingMapboxBody
from swagger_server.models.mastomys_natalensis_detection import MastomysNatalensisDetection
from swagger_server.models.mlpreprocessing_body import MlpreprocessingBody
from swagger_server.models.prediction_request import PredictionRequest
from swagger_server.models.prediction_request_prediction_parameters import PredictionRequestPredictionParameters
from swagger_server.models.prediction_result import PredictionResult
from swagger_server.models.remote_sensing_augmentation import RemoteSensingAugmentation
from swagger_server.models.remote_sensing_augmentation_parameters import RemoteSensingAugmentationParameters
from swagger_server.models.rodent_habitat_detection import RodentHabitatDetection
from swagger_server.models.temporal_analysis import TemporalAnalysis
