# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApiTrainmodelBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, model_type: Object=None, training_data: Object=None):  # noqa: E501
        """ApiTrainmodelBody - a model defined in Swagger

        :param model_type: The model_type of this ApiTrainmodelBody.  # noqa: E501
        :type model_type: Object
        :param training_data: The training_data of this ApiTrainmodelBody.  # noqa: E501
        :type training_data: Object
        """
        self.swagger_types = {
            'model_type': Object,
            'training_data': Object
        }

        self.attribute_map = {
            'model_type': 'model_type',
            'training_data': 'training_data'
        }
        self._model_type = model_type
        self._training_data = training_data

    @classmethod
    def from_dict(cls, dikt) -> 'ApiTrainmodelBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The api_trainmodel_body of this ApiTrainmodelBody.  # noqa: E501
        :rtype: ApiTrainmodelBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def model_type(self) -> Object:
        """Gets the model_type of this ApiTrainmodelBody.

        Model type to train  # noqa: E501

        :return: The model_type of this ApiTrainmodelBody.
        :rtype: Object
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type: Object):
        """Sets the model_type of this ApiTrainmodelBody.

        Model type to train  # noqa: E501

        :param model_type: The model_type of this ApiTrainmodelBody.
        :type model_type: Object
        """

        self._model_type = model_type

    @property
    def training_data(self) -> Object:
        """Gets the training_data of this ApiTrainmodelBody.

        Data for training the model  # noqa: E501

        :return: The training_data of this ApiTrainmodelBody.
        :rtype: Object
        """
        return self._training_data

    @training_data.setter
    def training_data(self, training_data: Object):
        """Sets the training_data of this ApiTrainmodelBody.

        Data for training the model  # noqa: E501

        :param training_data: The training_data of this ApiTrainmodelBody.
        :type training_data: Object
        """

        self._training_data = training_data
