# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApiAnomalydetectionBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, environmental_data: Object=None):  # noqa: E501
        """ApiAnomalydetectionBody - a model defined in Swagger

        :param environmental_data: The environmental_data of this ApiAnomalydetectionBody.  # noqa: E501
        :type environmental_data: Object
        """
        self.swagger_types = {
            'environmental_data': Object
        }

        self.attribute_map = {
            'environmental_data': 'environmental_data'
        }
        self._environmental_data = environmental_data

    @classmethod
    def from_dict(cls, dikt) -> 'ApiAnomalydetectionBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The api_anomalydetection_body of this ApiAnomalydetectionBody.  # noqa: E501
        :rtype: ApiAnomalydetectionBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def environmental_data(self) -> Object:
        """Gets the environmental_data of this ApiAnomalydetectionBody.

        Environmental data for anomaly detection  # noqa: E501

        :return: The environmental_data of this ApiAnomalydetectionBody.
        :rtype: Object
        """
        return self._environmental_data

    @environmental_data.setter
    def environmental_data(self, environmental_data: Object):
        """Sets the environmental_data of this ApiAnomalydetectionBody.

        Environmental data for anomaly detection  # noqa: E501

        :param environmental_data: The environmental_data of this ApiAnomalydetectionBody.
        :type environmental_data: Object
        """

        self._environmental_data = environmental_data
