# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApiDataenrichmentBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, external_data: Object=None):  # noqa: E501
        """ApiDataenrichmentBody - a model defined in Swagger

        :param external_data: The external_data of this ApiDataenrichmentBody.  # noqa: E501
        :type external_data: Object
        """
        self.swagger_types = {
            'external_data': Object
        }

        self.attribute_map = {
            'external_data': 'external_data'
        }
        self._external_data = external_data

    @classmethod
    def from_dict(cls, dikt) -> 'ApiDataenrichmentBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The api_dataenrichment_body of this ApiDataenrichmentBody.  # noqa: E501
        :rtype: ApiDataenrichmentBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def external_data(self) -> Object:
        """Gets the external_data of this ApiDataenrichmentBody.

        External data for enrichment  # noqa: E501

        :return: The external_data of this ApiDataenrichmentBody.
        :rtype: Object
        """
        return self._external_data

    @external_data.setter
    def external_data(self, external_data: Object):
        """Sets the external_data of this ApiDataenrichmentBody.

        External data for enrichment  # noqa: E501

        :param external_data: The external_data of this ApiDataenrichmentBody.
        :type external_data: Object
        """

        self._external_data = external_data
