# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AugmentationRemotesensingBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, augmentation_type: Object=None, parameters: Object=None):  # noqa: E501
        """AugmentationRemotesensingBody - a model defined in Swagger

        :param augmentation_type: The augmentation_type of this AugmentationRemotesensingBody.  # noqa: E501
        :type augmentation_type: Object
        :param parameters: The parameters of this AugmentationRemotesensingBody.  # noqa: E501
        :type parameters: Object
        """
        self.swagger_types = {
            'augmentation_type': Object,
            'parameters': Object
        }

        self.attribute_map = {
            'augmentation_type': 'augmentation_type',
            'parameters': 'parameters'
        }
        self._augmentation_type = augmentation_type
        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'AugmentationRemotesensingBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The augmentation_remotesensing_body of this AugmentationRemotesensingBody.  # noqa: E501
        :rtype: AugmentationRemotesensingBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def augmentation_type(self) -> Object:
        """Gets the augmentation_type of this AugmentationRemotesensingBody.

        Specifies the type of augmentation to apply.  # noqa: E501

        :return: The augmentation_type of this AugmentationRemotesensingBody.
        :rtype: Object
        """
        return self._augmentation_type

    @augmentation_type.setter
    def augmentation_type(self, augmentation_type: Object):
        """Sets the augmentation_type of this AugmentationRemotesensingBody.

        Specifies the type of augmentation to apply.  # noqa: E501

        :param augmentation_type: The augmentation_type of this AugmentationRemotesensingBody.
        :type augmentation_type: Object
        """

        self._augmentation_type = augmentation_type

    @property
    def parameters(self) -> Object:
        """Gets the parameters of this AugmentationRemotesensingBody.

        Additional parameters for augmentation, including resolution adjustments.  # noqa: E501

        :return: The parameters of this AugmentationRemotesensingBody.
        :rtype: Object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: Object):
        """Sets the parameters of this AugmentationRemotesensingBody.

        Additional parameters for augmentation, including resolution adjustments.  # noqa: E501

        :param parameters: The parameters of this AugmentationRemotesensingBody.
        :type parameters: Object
        """

        self._parameters = parameters
