# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CachingBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cache_type: Object=None, cache_duration: Object=None):  # noqa: E501
        """CachingBody - a model defined in Swagger

        :param cache_type: The cache_type of this CachingBody.  # noqa: E501
        :type cache_type: Object
        :param cache_duration: The cache_duration of this CachingBody.  # noqa: E501
        :type cache_duration: Object
        """
        self.swagger_types = {
            'cache_type': Object,
            'cache_duration': Object
        }

        self.attribute_map = {
            'cache_type': 'cache_type',
            'cache_duration': 'cache_duration'
        }
        self._cache_type = cache_type
        self._cache_duration = cache_duration

    @classmethod
    def from_dict(cls, dikt) -> 'CachingBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The caching_body of this CachingBody.  # noqa: E501
        :rtype: CachingBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cache_type(self) -> Object:
        """Gets the cache_type of this CachingBody.

        Type of caching mechanism, e.g., 'in-memory', 'disk'.  # noqa: E501

        :return: The cache_type of this CachingBody.
        :rtype: Object
        """
        return self._cache_type

    @cache_type.setter
    def cache_type(self, cache_type: Object):
        """Sets the cache_type of this CachingBody.

        Type of caching mechanism, e.g., 'in-memory', 'disk'.  # noqa: E501

        :param cache_type: The cache_type of this CachingBody.
        :type cache_type: Object
        """

        self._cache_type = cache_type

    @property
    def cache_duration(self) -> Object:
        """Gets the cache_duration of this CachingBody.

        Duration in seconds for how long the cache should be stored.  # noqa: E501

        :return: The cache_duration of this CachingBody.
        :rtype: Object
        """
        return self._cache_duration

    @cache_duration.setter
    def cache_duration(self, cache_duration: Object):
        """Sets the cache_duration of this CachingBody.

        Duration in seconds for how long the cache should be stored.  # noqa: E501

        :param cache_duration: The cache_duration of this CachingBody.
        :type cache_duration: Object
        """

        self._cache_duration = cache_duration
