# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2004(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result_url: Object=None):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger

        :param result_url: The result_url of this InlineResponse2004.  # noqa: E501
        :type result_url: Object
        """
        self.swagger_types = {
            'result_url': Object
        }

        self.attribute_map = {
            'result_url': 'result_url'
        }
        self._result_url = result_url

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
        :rtype: InlineResponse2004
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result_url(self) -> Object:
        """Gets the result_url of this InlineResponse2004.

        URL for downloading augmented data.  # noqa: E501

        :return: The result_url of this InlineResponse2004.
        :rtype: Object
        """
        return self._result_url

    @result_url.setter
    def result_url(self, result_url: Object):
        """Sets the result_url of this InlineResponse2004.

        URL for downloading augmented data.  # noqa: E501

        :param result_url: The result_url of this InlineResponse2004.
        :type result_url: Object
        """

        self._result_url = result_url
