# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002Data(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, predictions: Object=None):  # noqa: E501
        """InlineResponse2002Data - a model defined in Swagger

        :param predictions: The predictions of this InlineResponse2002Data.  # noqa: E501
        :type predictions: Object
        """
        self.swagger_types = {
            'predictions': Object
        }

        self.attribute_map = {
            'predictions': 'predictions'
        }
        self._predictions = predictions

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002Data':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2_data of this InlineResponse2002Data.  # noqa: E501
        :rtype: InlineResponse2002Data
        """
        return util.deserialize_model(dikt, cls)

    @property
    def predictions(self) -> Object:
        """Gets the predictions of this InlineResponse2002Data.


        :return: The predictions of this InlineResponse2002Data.
        :rtype: Object
        """
        return self._predictions

    @predictions.setter
    def predictions(self, predictions: Object):
        """Sets the predictions of this InlineResponse2002Data.


        :param predictions: The predictions of this InlineResponse2002Data.
        :type predictions: Object
        """

        self._predictions = predictions
