# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2006(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: Object=None, message: Object=None):  # noqa: E501
        """InlineResponse2006 - a model defined in Swagger

        :param status: The status of this InlineResponse2006.  # noqa: E501
        :type status: Object
        :param message: The message of this InlineResponse2006.  # noqa: E501
        :type message: Object
        """
        self.swagger_types = {
            'status': Object,
            'message': Object
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message'
        }
        self._status = status
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2006':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_6 of this InlineResponse2006.  # noqa: E501
        :rtype: InlineResponse2006
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> Object:
        """Gets the status of this InlineResponse2006.

        Status of context-aware configuration.  # noqa: E501

        :return: The status of this InlineResponse2006.
        :rtype: Object
        """
        return self._status

    @status.setter
    def status(self, status: Object):
        """Sets the status of this InlineResponse2006.

        Status of context-aware configuration.  # noqa: E501

        :param status: The status of this InlineResponse2006.
        :type status: Object
        """

        self._status = status

    @property
    def message(self) -> Object:
        """Gets the message of this InlineResponse2006.

        Confirmation message for successful setup.  # noqa: E501

        :return: The message of this InlineResponse2006.
        :rtype: Object
        """
        return self._message

    @message.setter
    def message(self, message: Object):
        """Sets the message of this InlineResponse2006.

        Confirmation message for successful setup.  # noqa: E501

        :param message: The message of this InlineResponse2006.
        :type message: Object
        """

        self._message = message
