# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200Data(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, habitat: Object=None, location: Object=None):  # noqa: E501
        """InlineResponse200Data - a model defined in Swagger

        :param habitat: The habitat of this InlineResponse200Data.  # noqa: E501
        :type habitat: Object
        :param location: The location of this InlineResponse200Data.  # noqa: E501
        :type location: Object
        """
        self.swagger_types = {
            'habitat': Object,
            'location': Object
        }

        self.attribute_map = {
            'habitat': 'habitat',
            'location': 'location'
        }
        self._habitat = habitat
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Data':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_data of this InlineResponse200Data.  # noqa: E501
        :rtype: InlineResponse200Data
        """
        return util.deserialize_model(dikt, cls)

    @property
    def habitat(self) -> Object:
        """Gets the habitat of this InlineResponse200Data.


        :return: The habitat of this InlineResponse200Data.
        :rtype: Object
        """
        return self._habitat

    @habitat.setter
    def habitat(self, habitat: Object):
        """Sets the habitat of this InlineResponse200Data.


        :param habitat: The habitat of this InlineResponse200Data.
        :type habitat: Object
        """

        self._habitat = habitat

    @property
    def location(self) -> Object:
        """Gets the location of this InlineResponse200Data.


        :return: The location of this InlineResponse200Data.
        :rtype: Object
        """
        return self._location

    @location.setter
    def location(self, location: Object):
        """Sets the location of this InlineResponse200Data.


        :param location: The location of this InlineResponse200Data.
        :type location: Object
        """

        self._location = location
