# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse20010(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, temperature: Object=None, humidity: Object=None, wind_speed: Object=None, weather_description: Object=None):  # noqa: E501
        """InlineResponse20010 - a model defined in Swagger

        :param temperature: The temperature of this InlineResponse20010.  # noqa: E501
        :type temperature: Object
        :param humidity: The humidity of this InlineResponse20010.  # noqa: E501
        :type humidity: Object
        :param wind_speed: The wind_speed of this InlineResponse20010.  # noqa: E501
        :type wind_speed: Object
        :param weather_description: The weather_description of this InlineResponse20010.  # noqa: E501
        :type weather_description: Object
        """
        self.swagger_types = {
            'temperature': Object,
            'humidity': Object,
            'wind_speed': Object,
            'weather_description': Object
        }

        self.attribute_map = {
            'temperature': 'temperature',
            'humidity': 'humidity',
            'wind_speed': 'wind_speed',
            'weather_description': 'weather_description'
        }
        self._temperature = temperature
        self._humidity = humidity
        self._wind_speed = wind_speed
        self._weather_description = weather_description

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20010':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_10 of this InlineResponse20010.  # noqa: E501
        :rtype: InlineResponse20010
        """
        return util.deserialize_model(dikt, cls)

    @property
    def temperature(self) -> Object:
        """Gets the temperature of this InlineResponse20010.

        Current temperature at the specified location.  # noqa: E501

        :return: The temperature of this InlineResponse20010.
        :rtype: Object
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: Object):
        """Sets the temperature of this InlineResponse20010.

        Current temperature at the specified location.  # noqa: E501

        :param temperature: The temperature of this InlineResponse20010.
        :type temperature: Object
        """

        self._temperature = temperature

    @property
    def humidity(self) -> Object:
        """Gets the humidity of this InlineResponse20010.

        Current humidity level at the specified location.  # noqa: E501

        :return: The humidity of this InlineResponse20010.
        :rtype: Object
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: Object):
        """Sets the humidity of this InlineResponse20010.

        Current humidity level at the specified location.  # noqa: E501

        :param humidity: The humidity of this InlineResponse20010.
        :type humidity: Object
        """

        self._humidity = humidity

    @property
    def wind_speed(self) -> Object:
        """Gets the wind_speed of this InlineResponse20010.

        Current wind speed at the specified location.  # noqa: E501

        :return: The wind_speed of this InlineResponse20010.
        :rtype: Object
        """
        return self._wind_speed

    @wind_speed.setter
    def wind_speed(self, wind_speed: Object):
        """Sets the wind_speed of this InlineResponse20010.

        Current wind speed at the specified location.  # noqa: E501

        :param wind_speed: The wind_speed of this InlineResponse20010.
        :type wind_speed: Object
        """

        self._wind_speed = wind_speed

    @property
    def weather_description(self) -> Object:
        """Gets the weather_description of this InlineResponse20010.

        Brief description of the current weather.  # noqa: E501

        :return: The weather_description of this InlineResponse20010.
        :rtype: Object
        """
        return self._weather_description

    @weather_description.setter
    def weather_description(self, weather_description: Object):
        """Sets the weather_description of this InlineResponse20010.

        Brief description of the current weather.  # noqa: E501

        :param weather_description: The weather_description of this InlineResponse20010.
        :type weather_description: Object
        """

        self._weather_description = weather_description
