# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MachineLearningModelHyperparameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, learning_rate: Object=None, batch_size: Object=None):  # noqa: E501
        """MachineLearningModelHyperparameters - a model defined in Swagger

        :param learning_rate: The learning_rate of this MachineLearningModelHyperparameters.  # noqa: E501
        :type learning_rate: Object
        :param batch_size: The batch_size of this MachineLearningModelHyperparameters.  # noqa: E501
        :type batch_size: Object
        """
        self.swagger_types = {
            'learning_rate': Object,
            'batch_size': Object
        }

        self.attribute_map = {
            'learning_rate': 'learning_rate',
            'batch_size': 'batch_size'
        }
        self._learning_rate = learning_rate
        self._batch_size = batch_size

    @classmethod
    def from_dict(cls, dikt) -> 'MachineLearningModelHyperparameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineLearningModel_hyperparameters of this MachineLearningModelHyperparameters.  # noqa: E501
        :rtype: MachineLearningModelHyperparameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def learning_rate(self) -> Object:
        """Gets the learning_rate of this MachineLearningModelHyperparameters.

        Learning rate for the model (e.g., 0.01)  # noqa: E501

        :return: The learning_rate of this MachineLearningModelHyperparameters.
        :rtype: Object
        """
        return self._learning_rate

    @learning_rate.setter
    def learning_rate(self, learning_rate: Object):
        """Sets the learning_rate of this MachineLearningModelHyperparameters.

        Learning rate for the model (e.g., 0.01)  # noqa: E501

        :param learning_rate: The learning_rate of this MachineLearningModelHyperparameters.
        :type learning_rate: Object
        """

        self._learning_rate = learning_rate

    @property
    def batch_size(self) -> Object:
        """Gets the batch_size of this MachineLearningModelHyperparameters.

        Batch size for training (e.g., 32)  # noqa: E501

        :return: The batch_size of this MachineLearningModelHyperparameters.
        :rtype: Object
        """
        return self._batch_size

    @batch_size.setter
    def batch_size(self, batch_size: Object):
        """Sets the batch_size of this MachineLearningModelHyperparameters.

        Batch size for training (e.g., 32)  # noqa: E501

        :param batch_size: The batch_size of this MachineLearningModelHyperparameters.
        :type batch_size: Object
        """

        self._batch_size = batch_size
