# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MappingMapboxBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, coordinates: Object=None, overlays: Object=None):  # noqa: E501
        """MappingMapboxBody - a model defined in Swagger

        :param coordinates: The coordinates of this MappingMapboxBody.  # noqa: E501
        :type coordinates: Object
        :param overlays: The overlays of this MappingMapboxBody.  # noqa: E501
        :type overlays: Object
        """
        self.swagger_types = {
            'coordinates': Object,
            'overlays': Object
        }

        self.attribute_map = {
            'coordinates': 'coordinates',
            'overlays': 'overlays'
        }
        self._coordinates = coordinates
        self._overlays = overlays

    @classmethod
    def from_dict(cls, dikt) -> 'MappingMapboxBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The mapping_mapbox_body of this MappingMapboxBody.  # noqa: E501
        :rtype: MappingMapboxBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def coordinates(self) -> Object:
        """Gets the coordinates of this MappingMapboxBody.

        Array of coordinates to plot on the Mapbox map.  # noqa: E501

        :return: The coordinates of this MappingMapboxBody.
        :rtype: Object
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates: Object):
        """Sets the coordinates of this MappingMapboxBody.

        Array of coordinates to plot on the Mapbox map.  # noqa: E501

        :param coordinates: The coordinates of this MappingMapboxBody.
        :type coordinates: Object
        """

        self._coordinates = coordinates

    @property
    def overlays(self) -> Object:
        """Gets the overlays of this MappingMapboxBody.

        List of overlay layers, such as habitat or vegetation coverage.  # noqa: E501

        :return: The overlays of this MappingMapboxBody.
        :rtype: Object
        """
        return self._overlays

    @overlays.setter
    def overlays(self, overlays: Object):
        """Sets the overlays of this MappingMapboxBody.

        List of overlay layers, such as habitat or vegetation coverage.  # noqa: E501

        :param overlays: The overlays of this MappingMapboxBody.
        :type overlays: Object
        """

        self._overlays = overlays
