# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.rodent_habitat_detection import RodentHabitatDetection  # noqa: F401,E501
from swagger_server import util


class MastomysNatalensisDetection(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, location_coordinates: RodentHabitatDetection=None, image_data: Object=None, environmental_data: RodentHabitatDetection=None, habitat_suitability: RodentHabitatDetection=None):  # noqa: E501
        """MastomysNatalensisDetection - a model defined in Swagger

        :param location_coordinates: The location_coordinates of this MastomysNatalensisDetection.  # noqa: E501
        :type location_coordinates: RodentHabitatDetection
        :param image_data: The image_data of this MastomysNatalensisDetection.  # noqa: E501
        :type image_data: Object
        :param environmental_data: The environmental_data of this MastomysNatalensisDetection.  # noqa: E501
        :type environmental_data: RodentHabitatDetection
        :param habitat_suitability: The habitat_suitability of this MastomysNatalensisDetection.  # noqa: E501
        :type habitat_suitability: RodentHabitatDetection
        """
        self.swagger_types = {
            'location_coordinates': RodentHabitatDetection,
            'image_data': Object,
            'environmental_data': RodentHabitatDetection,
            'habitat_suitability': RodentHabitatDetection
        }

        self.attribute_map = {
            'location_coordinates': 'location_coordinates',
            'image_data': 'image_data',
            'environmental_data': 'environmental_data',
            'habitat_suitability': 'habitat_suitability'
        }
        self._location_coordinates = location_coordinates
        self._image_data = image_data
        self._environmental_data = environmental_data
        self._habitat_suitability = habitat_suitability

    @classmethod
    def from_dict(cls, dikt) -> 'MastomysNatalensisDetection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MastomysNatalensisDetection of this MastomysNatalensisDetection.  # noqa: E501
        :rtype: MastomysNatalensisDetection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def location_coordinates(self) -> RodentHabitatDetection:
        """Gets the location_coordinates of this MastomysNatalensisDetection.


        :return: The location_coordinates of this MastomysNatalensisDetection.
        :rtype: RodentHabitatDetection
        """
        return self._location_coordinates

    @location_coordinates.setter
    def location_coordinates(self, location_coordinates: RodentHabitatDetection):
        """Sets the location_coordinates of this MastomysNatalensisDetection.


        :param location_coordinates: The location_coordinates of this MastomysNatalensisDetection.
        :type location_coordinates: RodentHabitatDetection
        """

        self._location_coordinates = location_coordinates

    @property
    def image_data(self) -> Object:
        """Gets the image_data of this MastomysNatalensisDetection.

        Base64 encoded image data for detection.  # noqa: E501

        :return: The image_data of this MastomysNatalensisDetection.
        :rtype: Object
        """
        return self._image_data

    @image_data.setter
    def image_data(self, image_data: Object):
        """Sets the image_data of this MastomysNatalensisDetection.

        Base64 encoded image data for detection.  # noqa: E501

        :param image_data: The image_data of this MastomysNatalensisDetection.
        :type image_data: Object
        """

        self._image_data = image_data

    @property
    def environmental_data(self) -> RodentHabitatDetection:
        """Gets the environmental_data of this MastomysNatalensisDetection.


        :return: The environmental_data of this MastomysNatalensisDetection.
        :rtype: RodentHabitatDetection
        """
        return self._environmental_data

    @environmental_data.setter
    def environmental_data(self, environmental_data: RodentHabitatDetection):
        """Sets the environmental_data of this MastomysNatalensisDetection.


        :param environmental_data: The environmental_data of this MastomysNatalensisDetection.
        :type environmental_data: RodentHabitatDetection
        """

        self._environmental_data = environmental_data

    @property
    def habitat_suitability(self) -> RodentHabitatDetection:
        """Gets the habitat_suitability of this MastomysNatalensisDetection.


        :return: The habitat_suitability of this MastomysNatalensisDetection.
        :rtype: RodentHabitatDetection
        """
        return self._habitat_suitability

    @habitat_suitability.setter
    def habitat_suitability(self, habitat_suitability: RodentHabitatDetection):
        """Sets the habitat_suitability of this MastomysNatalensisDetection.


        :param habitat_suitability: The habitat_suitability of this MastomysNatalensisDetection.
        :type habitat_suitability: RodentHabitatDetection
        """

        self._habitat_suitability = habitat_suitability
