# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RemoteSensingAugmentationParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, resolution: Object=None, additional_param: Object=None):  # noqa: E501
        """RemoteSensingAugmentationParameters - a model defined in Swagger

        :param resolution: The resolution of this RemoteSensingAugmentationParameters.  # noqa: E501
        :type resolution: Object
        :param additional_param: The additional_param of this RemoteSensingAugmentationParameters.  # noqa: E501
        :type additional_param: Object
        """
        self.swagger_types = {
            'resolution': Object,
            'additional_param': Object
        }

        self.attribute_map = {
            'resolution': 'resolution',
            'additional_param': 'additional_param'
        }
        self._resolution = resolution
        self._additional_param = additional_param

    @classmethod
    def from_dict(cls, dikt) -> 'RemoteSensingAugmentationParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RemoteSensingAugmentation_parameters of this RemoteSensingAugmentationParameters.  # noqa: E501
        :rtype: RemoteSensingAugmentationParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resolution(self) -> Object:
        """Gets the resolution of this RemoteSensingAugmentationParameters.

        Resolution of the augmentation process  # noqa: E501

        :return: The resolution of this RemoteSensingAugmentationParameters.
        :rtype: Object
        """
        return self._resolution

    @resolution.setter
    def resolution(self, resolution: Object):
        """Sets the resolution of this RemoteSensingAugmentationParameters.

        Resolution of the augmentation process  # noqa: E501

        :param resolution: The resolution of this RemoteSensingAugmentationParameters.
        :type resolution: Object
        """

        self._resolution = resolution

    @property
    def additional_param(self) -> Object:
        """Gets the additional_param of this RemoteSensingAugmentationParameters.

        Any additional parameter  # noqa: E501

        :return: The additional_param of this RemoteSensingAugmentationParameters.
        :rtype: Object
        """
        return self._additional_param

    @additional_param.setter
    def additional_param(self, additional_param: Object):
        """Sets the additional_param of this RemoteSensingAugmentationParameters.

        Any additional parameter  # noqa: E501

        :param additional_param: The additional_param of this RemoteSensingAugmentationParameters.
        :type additional_param: Object
        """

        self._additional_param = additional_param
