# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.remote_sensing_augmentation_parameters import RemoteSensingAugmentationParameters  # noqa: F401,E501
from swagger_server import util


class RemoteSensingAugmentation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, augmentation_type: Object=None, parameters: RemoteSensingAugmentationParameters=None):  # noqa: E501
        """RemoteSensingAugmentation - a model defined in Swagger

        :param augmentation_type: The augmentation_type of this RemoteSensingAugmentation.  # noqa: E501
        :type augmentation_type: Object
        :param parameters: The parameters of this RemoteSensingAugmentation.  # noqa: E501
        :type parameters: RemoteSensingAugmentationParameters
        """
        self.swagger_types = {
            'augmentation_type': Object,
            'parameters': RemoteSensingAugmentationParameters
        }

        self.attribute_map = {
            'augmentation_type': 'augmentation_type',
            'parameters': 'parameters'
        }
        self._augmentation_type = augmentation_type
        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'RemoteSensingAugmentation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RemoteSensingAugmentation of this RemoteSensingAugmentation.  # noqa: E501
        :rtype: RemoteSensingAugmentation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def augmentation_type(self) -> Object:
        """Gets the augmentation_type of this RemoteSensingAugmentation.

        Specifies the type of augmentation, including specific detection for Mastomys natalensis.  # noqa: E501

        :return: The augmentation_type of this RemoteSensingAugmentation.
        :rtype: Object
        """
        return self._augmentation_type

    @augmentation_type.setter
    def augmentation_type(self, augmentation_type: Object):
        """Sets the augmentation_type of this RemoteSensingAugmentation.

        Specifies the type of augmentation, including specific detection for Mastomys natalensis.  # noqa: E501

        :param augmentation_type: The augmentation_type of this RemoteSensingAugmentation.
        :type augmentation_type: Object
        """

        self._augmentation_type = augmentation_type

    @property
    def parameters(self) -> RemoteSensingAugmentationParameters:
        """Gets the parameters of this RemoteSensingAugmentation.


        :return: The parameters of this RemoteSensingAugmentation.
        :rtype: RemoteSensingAugmentationParameters
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: RemoteSensingAugmentationParameters):
        """Sets the parameters of this RemoteSensingAugmentation.


        :param parameters: The parameters of this RemoteSensingAugmentation.
        :type parameters: RemoteSensingAugmentationParameters
        """

        self._parameters = parameters
